#!/bin/bash
pictdir="$HOME/Pictures/Wallpapers/"
time=30m

#Exit if the script is already running, just in case
#Got this part of script somewhere in this forum
if pidof -x $(basename $0) > /dev/null; then
  for p in $(pidof -x $(basename $0)); do
    if [ $p -ne $$ ]; then
      echo "Script $0 is already running: exiting"
      exit
    fi
  done
fi

# List wallpapers in a specific directory
let count=1
picarray=();
while true
do
	for f in "$pictdir"*
	do
	    gsettings set org.gnome.desktop.background picture-uri "$pictdir$(basename "$f")"
	    sleep $time #wait for $time second(s)
	done
done
